### ISSUE TITLE
security : place-picker API Key exposed

### ISSUE THREAD

**Issue by ghost** [implude/local-community-android#2]
[https://github.com/implude/local-community-android/commit/4421f51d4f164093f800a0c73bc9844fbb8a0b6c](url)

After action please reply

**Comment by ksh1743** [comment]
@wkdwhddn06 API키 같은 private value 따로 저장할 수 있나요?
string.xml에 import하는 방법 같은거

**Comment by wkdwhddn06** [comment]
> @wkdwhddn06 API키 같은 private value 따로 저장할 수 있나요?
> string.xml에 import하는 방법 같은거

secret.property 파일을 따로 만들고 그 파일을 .gitignore에 등록한다음에 BuildConfig를 이용해서 키 값을 불러오면 됩니다. 자세한 방법은 인터넷으로 찾아보거나 학교가면 알려줄게요.

**Comment by ghost** [comment]
@wkdwhddn06 본인이 본인을 태그하시네요...
저 댓글 제가 단겁니다.. ㅎㅎ

**Comment by wkdwhddn06** [comment]
> @wkdwhddn06 본인이 본인을 태그하시네요...
> 저 댓글 제가 단겁니다.. ㅎㅎ

아 답장기능인데;; 뭐 알겠습니다

**Comment by MinSeungHyun** [comment]
> @wkdwhddn06 API키 같은 private value 따로 저장할 수 있나요?
> string.xml에 import하는 방법 같은거

종우가 말한것처럼 property 파일에 저장할 수도 있고, res/values에 secrets.xml 파일 만들어서 string 리소스로 저장하고 gitignore에 추가하는 방법이 있습니다. 상황에 따라 더 편한 방법으로 하면 될 것 같습니다.
https://github.com/codepath/android_guides/wiki/Storing-Secret-Keys-in-Android
